debug: false
root: /da/
exitpage: /
db:
  prefix: postgresql+psycopg2://
  name: docassemble
  user: null
  password: null
  host: null
  port: null
  table_prefix: null
oauth:
  facebook:
    enable: false
    id: 423759825983740
    secret: 34993a09909c0909b9000a090d09f099
  google:
    enable: false
    id: 23123018240-32239fj28fj4fuhf394h3984eurhfurh.apps.googleusercontent.com
    secret: DGE34gdgerg3GDG545tgdfRf
secretkey: 28asflwjeifwlfjsd2fejfiefw3g4o87
appname: docassemble
brandname: docassemble
uploads: /usr/share/docassemble/files
packages: /usr/share/docassemble/local
packagecache: /usr/share/docassemble/cache
webapp: /usr/share/docassemble/webapp/docassemble.wsgi
certs: /usr/share/docassemble/certs
mail:
  default_sender: '"Administrator" <no-reply@example.com>'
use_progress_bar: false
imagemagick: convert
pdftoppm: pdftoppm
pacpl: pacpl
avconv: avconv
default_interview: docassemble.demo:data/questions/questions.yml
flask_log: /tmp/flask.log
language: en
locale: US.utf8
default_admin_account:
  nickname: admin
  email: admin@admin.com
  password: password
voicerss:
  enable: false
  key: ae8734983948ebc98239e9898f998432
  languages:
    en: us
    es: mx
    fr: fr
s3:
  enable: false
  access_key_id: FWIEJFIJIDGISEJFWOEF
  secret_access_key: RGERG34eeeg3agwetTR0+wewWAWEFererNRERERG
  bucket: yourbucketname
ec2: false
words:
  - docassemble.base:data/translations/us-words.yml
