debug: false
root: /demo
exitpage: /
db:
  prefix: postgresql+psycopg2://
  name: docassemble
  user: null
  password: null
  host: null
  port: null
oauth:
  facebook:
    enable: false
    id: 423759825983740
    secret: 34993a09909c0909b9000a090d09f099
  google:
    enable: false
    id: 23123018240-32239fj28fj4fuhf394h3984eurhfurh.apps.googleusercontent.com
    secret: DGE34gdgerg3GDG545tgdfRf
secretkey: 28asflwjeifwlfjsd2fejfiefw3g4o87
appname: docassemble
brandname: demo
uploads: /usr/share/docassemble/files
webapp: /var/lib/docassemble/flask.wsgi
mail:
  default_sender: '"Administrator" <no-reply@example.com>'
admin_address: '"Administrator" <admin@example.com>'
use_progress_bar: false
imagemagick: convert
default_interview: docassemble.demo:data/questions/questions.yml
flask_log: /tmp/flask.log
language: en
locale: US.utf8
default_admin_account:
  nickname: admin
  email: admin@admin.com
  password: password