url root: http://localhost
exitpage: /
db:
  prefix: postgresql+psycopg2://
  name: docassemble
  user: docassemble
  password: abc123
  host: localhost
  port: null
  table_prefix: null
oauth:
  facebook:
    enable: false
    id: 423759825983740
    secret: 34993a09909c0909b9000a090d09f099
  google:
    enable: false
    id: 23123018240-32239fj28fj4fuhf394h3984eurhfurh.apps.googleusercontent.com
    secret: DGE34gdgerg3GDG545tgdfRf
secretkey: 28asflwjeifwlfjsd2fejfiefw3g4o87
default_title: docassemble
default_short_title: doc
mail:
  username: null
  password: null
  server: localhost
  default_sender: '"Administrator" <no-reply@example.com>'
default_interview: docassemble.demo:data/questions/questions.yml
language: en
locale: en_US.utf8
default_admin_account:
  email: admin@admin.com
  password: password
voicerss:
  enable: false
  key: ae8734983948ebc98239e9898f998432
  languages:
    en: us
    es: mx
    fr: fr
s3:
  enable: false
  access_key_id: FWIEJFIJIDGISEJFWOEF
  secret_access_key: RGERG34eeeg3agwetTR0+wewWAWEFererNRERERG
  bucket: yourbucketname
ec2: false
words:
  - docassemble.base:data/sources/us-words.yml
