debug: false
root: /da/
exitpage: /
db:
  prefix: postgresql+psycopg2://
  name: docassemble
  user: null
  password: null
  host: null
  port: null
  table_prefix: null
oauth:
  facebook:
    enable: false
    id: 423759825983740
    secret: 34993a09909c0909b9000a090d09f099
  google:
    enable: false
    id: 23123018240-32239fj28fj4fuhf394h3984eurhfurh.apps.googleusercontent.com
    secret: DGE34gdgerg3GDG545tgdfRf
secretkey: 28asflwjeifwlfjsd2fejfiefw3g4o87
appname: docassemble
brandname: docassemble
uploads: /usr/share/docassemble/files
packages: /usr/share/docassemble/local
packagecache: /usr/share/docassemble/cache
webapp: /usr/share/docassemble/webapp/docassemble.wsgi
mail:
  default_sender: '"Administrator" <no-reply@example.com>'
use_progress_bar: false
imagemagick: convert
pdftoppm: pdftoppm
pacpl: pacpl
avconv: avconv
default_interview: docassemble.demo:data/questions/questions.yml
flask_log: /tmp/flask.log
language: en
locale: US.utf8
default_admin_account:
  nickname: admin
  email: admin@admin.com
  password: password
voicerss:
  enable: false
  key: 347593849874e7454b9872948a87987d
  languages:
    en:
      GB: en-gb
      US: en-us
    es:
      MX: es-mx
    fr:
      FR: fr-fr
